version: "3"

services:
   
    api:
      container_name: "api"
      build: ./docker
      volumes:
        - ./server:/app
      tty: true
      ports:
        - 8000:8000
      command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8000